version: '3'

services:
  # t4_front:
  #   build:
  #     context: ./t4_front/
  #     dockerfile: dev.Dockerfile
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - './t4_front:/t4_front'
  t4_server:
    build:
      context: ./t4_server/
      dockerfile: dev.Dockerfile
    volumes:
      - './t4_server:/t4_server'
    ports:
      - '8070:8070'
    links:
      - mongo
    networks: 
      - netDb
  mongo:
    image: mongo:latest
    # build:
    #   context: ./Mongo/
    #   dockerfile: dev.Dockerfile
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - .Mongo/data/dev:/data/db
    networks: 
      - netDb
    # command: mongod
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
    links:
      - mongo
    networks: 
      - netDb

networks:
  netDb:
    driver: "bridge"


